config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :places do
    resources :bookings, only: %i[create]
  end


  resources :detail_compatibilities, only: %i[create show new edit update] do
    collection do
      patch :update_user_preferences
    end
  end

  resources :users, only: :show

  get 'profile', to: 'users#show_profile', as: :user_profile
  get 'profile/edit', to: 'users#edit_profile', as: :edit_user_profile
  patch 'profile', to: 'users#update_profile'


  patch "bookings/:id", to: "bookings#accept", as: :accept
  patch "bookings/:id", to: "bookings#decline", as: :decline

  resources :bookings, only: [:show] do
    resources :messages, only: [:create]
  end

  get 'my_places', to: 'places#my_places', as: :my_places

end

app/models/detail_compatibility.rb
class DetailCompatibility < ApplicationRecord
  belongs_to :user
  belongs_to :compatibility
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :detail_compatibilities, dependent: :destroy
  has_many :compatibilities, through: :detail_compatibilities
  has_one_attached :photo

  # validates :first_name, :last_name, :email, :password, :birth_date, :gender, :bio, :ocupation, presence: true

  def self.find_compatible_users(current_user)
    current_user_compatibilities = current_user.compatibilities.pluck(:id)
    return [] if current_user_compatibilities.empty?

    User.where.not(id: current_user.id).includes(:compatibilities).map do |user|
      user_compatibilities = user.compatibilities.pluck(:id)
      next if user_compatibilities.empty?

      shared = (current_user_compatibilities & user_compatibilities).size
      total_possible = [current_user_compatibilities.size, user_compatibilities.size].min
      match_percentage = (shared.to_f / total_possible * 100).round

      {
        user: user,
        shared_compatibilities: Compatibility.where(id: (current_user_compatibilities & user_compatibilities)),
        match_percentage: match_percentage
      }
    end.compact.sort_by { |match| -match[:match_percentage] }
  end

  def compatibility_percentage_with(other_user)
    return 0 if self == other_user

    my_compat = compatibilities.pluck(:id)
    other_compat = other_user.compatibilities.pluck(:id)
    return 0 if my_compat.empty? || other_compat.empty?

    shared = (my_compat & other_compat).size
    total_possible = [my_compat.size, other_compat.size].min
    (shared.to_f / total_possible * 100).round
  end
end

app/controllers/detail_compatibilities_controller.rb
class DetailCompatibilitiesController < ApplicationController
  def show
    authorize DetailCompatibility
    @compatibilities = Compatibility.all
  end

  def new
    authorize DetailCompatibility
    @compatibilities = Compatibility.all
  end

  def create
    authorize DetailCompatibility
    @compatibilities = params[:compatibilities] || 0
    if @compatibilities.size < 10
      @compatibilities = Compatibility.all
      flash.now[:alert] = "Debes seleccionar al menos 10 compatibilidades."
      render :new, status: :unprocessable_entity
    else
      @compatibilities.each do |c|
        DetailCompatibility.create(compatibility_id: c, user: current_user)
      end
      redirect_to root_path
    end
  end

  def edit
    @detail_compatibility = DetailCompatibility.find(params[:id])
    authorize @detail_compatibility
    @compatibilities = Compatibility.all
  end

  def update_user_preferences
    authorize DetailCompatibility
    selected_ids = params[:compatibilities] || []

    if selected_ids.size < 10
      flash.now[:alert] = "Debes seleccionar al menos 10 compatibilidades."
      @compatibilities = Compatibility.all
      render :edit, status: :unprocessable_entity
    else
      current_user.compatibility_ids = selected_ids
      flash[:notice] = "Preferencias actualizadas correctamente."
      redirect_to places_path
    end
  end

  private

  def detail_compatibility_params
    params.require(:detail_compatibility).permit(:compatibility_id, :user_id)
  end
end

app/views/detail_compatibilities/edit.html.erb
<div class="mb-1 mt-5">
  <h3 class="check-box-title">Personaliza tus preferencias</h3>
</div>

  <%= form_with url: update_user_preferences_detail_compatibilities_path, method: :patch do %>
    <div class="organization">
      <div class="half">
        <div>
          <% @compatibilities.each do |c| %>
            <div class="form-check form-check-inline">
              <%= check_box_tag "compatibilities[]", c.id, current_user.compatibility_ids.include?(c.id), id: "option-#{c.title}", class: "compatibility-question" %>
              <%= label_tag "option-#{c.title}", class: "m-2" do %>
                <i class="<%= c.icon %>"></i> <%= c.title_spanish %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>


    </div>
    <div class="boton-save">
        <%= submit_tag "Guardar preferencias", class: "btn-detail-compatibility" %>
      </div>
</div>
<% end %>

app/views/detail_compatibilities/new.html.erb
<div class="container mt-5">
      <h1 class="place-titulo">Selecciona tus gustos para encontrar tu Roomatch ideal <i class="fa-solid fa-rocket"></i> </h1>
</div>


<%= form_with url: detail_compatibilities_path, method: :post do %>
  <div class="organization">
    <div class="half">
      <div class="">
        <% @compatibilities.each do |c| %>
          <div class="form-check form-check-inline">
            <%= check_box_tag "compatibilities[]", c.id, false, id: "option-#{c.title}", class: "compatibility-question" %>
            <%= label_tag "option-#{c.title}", class: "m-2" do %>
              <i class="<%= c.icon %>"></i> <%= c.title_spanish %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>


  </div>
   <div class="boton-save">
      <%= submit_tag "Guardar mis gustos", class: "btn-detail-compatibility" %>
    </div>
<% end %>

app/views/detail_compatibilities/show.html.erb
<%# Para verlo es en http://127.0.0.1:3000/detail_compatibilities/:id %>